[build]
  command = "chmod +x node_modules/.bin/react-scripts && npm run build"
  publish = "build"
  environment = { NODE_VERSION = "20" }

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200